//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTBAPISERVER.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpFileShare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbpFileShare()
        {
            this.AbpSharePermissions = new HashSet<AbpSharePermission>();
        }
    
        public int Id { get; set; }
        public int ServerId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string ShareGUID { get; set; }
        public string SharedPath { get; set; }
        public string SharedAgent { get; set; }
        public string SharedFriendlyName { get; set; }
        public Nullable<int> SharedStatus { get; set; }
        public string MountPath { get; set; }
        public Nullable<int> MaxUsers { get; set; }
        public Nullable<bool> AutoControl { get; set; }
        public Nullable<bool> HiddenShare { get; set; }
        public Nullable<bool> IgnorePermission { get; set; }
        public Nullable<bool> AccessBasedEnumeration { get; set; }
        public Nullable<int> ClientCacheType { get; set; }
        public Nullable<int> ShareType { get; set; }
        public Nullable<bool> ShareSubDirectories { get; set; }
        public string UserPermissions { get; set; }
        public string ShareComments { get; set; }
    
        public virtual AbpServer AbpServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbpSharePermission> AbpSharePermissions { get; set; }
    }
}
