//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTBAPISERVER.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpSharePermission
    {
        public int Id { get; set; }
        public long UserId { get; set; }
        public int SharedId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string Name { get; set; }
        public bool AllAccess { get; set; }
        public bool ReadOnly { get; set; }
        public bool WriteOnly { get; set; }
        public bool RenameOnly { get; set; }
        public bool CanDelete { get; set; }
        public bool CanCache { get; set; }
        public int MaxFiles { get; set; }
        public int MaxConnections { get; set; }
        public string DenyFileType { get; set; }
        public bool IsGranted { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual AbpFileShare AbpFileShare { get; set; }
        public virtual AbpRole AbpRole { get; set; }
        public virtual AbpUser AbpUser { get; set; }
    }
}
