//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTBAPISERVER.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbpServer()
        {
            this.AbpFileShares = new HashSet<AbpFileShare>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string ServerGUID { get; set; }
        public string Name { get; set; }
        public string IpAddress { get; set; }
        public string ServerPath { get; set; }
        public string AdminEmail { get; set; }
        public string AdminName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbpFileShare> AbpFileShares { get; set; }
        public virtual AbpTenant AbpTenant { get; set; }
    }
}
